import type { Tool } from "../../types";

export const ascToCsv: Tool = {
	id: "document/asc-to-csv",
	slug: "asc-to-csv",
	category: "document",
	kind: "convert",
	accept: {
		mime: ["text/plain", "application/octet-stream"],
		ext: ["asc"],
	},
	output: { ext: "csv", mime: "text/csv" },
	engines: ["extract:asc-to-csv"],
	quality: {
		losslessAvailable: true,
		defaultPreset: "csv",
		presets: [
			{
				id: "csv",
				label: "CSV Spreadsheet (.csv)",
				explanation:
					"Formats timestamps, channels, 11-bit and 29-bit CAN IDs, direction flags, and byte payloads into an RFC 4180 CSV spreadsheet.",
				params: { json: false },
			},
			{
				id: "json",
				label: "Structured JSON (.json)",
				explanation:
					"Exports frames as an array of structured JSON objects with hexadecimal and decimal identifiers.",
				params: { json: true },
			},
		],
		advanced: [],
	},
	seo: {
		title: "ASC to CSV — Convert Vector CAN Bus Trace to Spreadsheet | convrtr",
		h1: "Convert Vector CANoe ASC Bus Trace to CSV",
		intent:
			"Convert Vector CANoe / CANalyzer ASCII (.asc) automotive bus trace logs into clean CSV spreadsheets and JSON without expensive Vector software. Open CAN, CAN-FD, and J1939 vehicle telemetry directly in Excel or Google Sheets.",
		faq: [
			{
				q: "What is a Vector .asc file?",
				a: "A Vector .asc file is an ASCII text trace generated by CANoe, CANalyzer, and vehicle loggers recording timestamped CAN, CAN-FD, and LIN bus message traffic across automotive electronic control units (ECUs).",
			},
			{
				q: "Can I open the resulting CSV in Microsoft Excel or Python pandas?",
				a: "Yes. The generated CSV strictly follows RFC 4180 with standard numeric microsecond timestamps, hex/dec identifiers, and individual byte columns (b0 through b7), making it immediately usable in Excel, Numbers, and pandas.",
			},
			{
				q: "Are CAN-FD and extended 29-bit IDs supported?",
				a: "Yes. Both standard 11-bit identifiers and 29-bit extended frames (ending in 'x'), as well as CAN-FD variable-length payloads, are recognized and extracted.",
			},
			{
				q: "Is sensitive vehicle diagnostic data private?",
				a: "Yes. All parsing executes 100% locally in your browser. Proprietary vehicle telemetry, VIN numbers, and diagnostic frames are never transmitted over the internet.",
			},
		],
		related: [
			"document/adif-to-csv",
			"document/fit-to-csv",
			"document/vcf-to-csv",
		],
	},
};
