import type { Tool } from "../../types";

export const xwdToPng: Tool = {
	id: "image/xwd-to-png",
	slug: "xwd-to-png",
	category: "image",
	kind: "extract",
	accept: {
		mime: [
			"image/x-xwindowdump",
			"image/xwd",
			"image/x-xwd",
			"application/x-xwd",
			"application/octet-stream",
		],
		ext: ["xwd", "xdump"],
	},
	output: { ext: "png", mime: "image/png" },
	engines: ["extract:xwd-to-png"],
	quality: {
		losslessAvailable: true,
		defaultPreset: "lossless",
		presets: [
			{
				id: "lossless",
				label: "Lossless 32-bit RGBA PNG",
				explanation:
					"Decodes X Window System Window Dump (.xwd) bitmaps, pixmaps, and colormaps into standard 32-bit RGBA PNG.",
				params: {},
			},
		],
		advanced: [],
	},
	seo: {
		title: "XWD to PNG — Convert X Window Dump (.xwd, .xdump) to PNG | convrtr",
		h1: "Convert XWD Window Dumps to PNG",
		intent:
			"Convert X11 / X Window System window dumps (.xwd, .xdump) from Unix workstations, Xvfb headless servers, and vintage desktops into crisp lossless PNG in your browser. 100% private with zero server uploads.",
		faq: [
			{
				q: "What is an XWD (.xwd) file?",
				a: "XWD (X Window Dump) is the native raster screen capture format of the X Window System (X11). Generated by the standard xwd command-line utility, Xvfb virtual framebuffers, and Unix workstations, it captures window hierarchies, visual colormaps, and pixmap bitplanes.",
			},
			{
				q: "What color depths and formats are supported?",
				a: "convrtr decodes 1-bit monochrome bitmaps (XYBitmap/ZPixmap), 8-bit PseudoColor paletted graphics with custom XColor colormaps, 16-bit RGB, and 24/32-bit TrueColor/DirectColor bitplanes across both MSBFirst and LSBFirst byte orders.",
			},
			{
				q: "Why convert XWD to PNG?",
				a: "Modern operating systems (macOS, Windows, iOS, Android) and web browsers cannot natively render XWD files. Converting to PNG allows you to view, share, and archive legacy Unix screenshots and headless CI screen captures anywhere.",
			},
			{
				q: "Are my window dumps uploaded to any remote server?",
				a: "Never. All 100-byte header parsing, color map lookups, bitmask unpacks, and PNG compression happen strictly inside your browser memory.",
			},
		],
		related: [
			"image/xpm-to-png",
			"image/xbm-to-png",
			"image/ras-to-png",
			"image/sgi-to-png",
		],
	},
};
